### ISSUE TITLE
How to move an object Transform (no mesh) ?

### ISSUE THREAD

**Issue by nathanvogel** [keenanwoodall/Deform#23]
Hi,
I would like to transform the position + rotation of a GameObject (a camera) along with the deformation of a mesh. Is there a way to do that?

Thank you for this ++ asset!

**Comment by keenanwoodall** [comment]
I'm not sure if I know exactly what you're trying to do, but if you want an effect to follow the camera perfectly you could just make the deformer object a child of the camera. Feel free to explain your goal further if I'm misunderstanding :+1:

**Comment by nathanvogel** [comment]
Sorry I'll try to be clearer 👍  I want to do something like this:
![example-bend](https://user-images.githubusercontent.com/3106715/67396372-61bea500-f59f-11e9-944c-31b462b06d6b.png)

black = before
red = after deform

The line is the deformed mesh and the camera is another independant object.

**Comment by keenanwoodall** [comment]
I gotcha. So the camera needs to be deformed as if it's a vertice on the mesh. There isn't currently a way to do this with deform, but I'll look into parenting objects to vertices as I think that's a useful feature. When I get the time I'll try and make a hacky temporary script you can use in the meantime.

**Comment by nathanvogel** [comment]
Awesome! Thanks for the help :)

**Comment by keenanwoodall** [comment]
@nathanvogel Sorry for the delay. I threw together a quick and dirty script (emphasis on dirty). It's not super easy to use but, just drop it on an object, give it a reference to a Deformable component, and increase the `triangle index` property until the triangle you want is selected. (sorry I know that's lame) The object will be pinned to that triangle. Do note: I **didn't** add control for changing rotation/position offsets. They shouldn't be hard to add, but I figured it'd be easier to attach an empty object to the triangle and then add the camera as a child. Then you can change the offsets via the scene transform handles rather than fiddling with offsets in the inspector.

I needed to expose the mesh data to be able to access the triangles (without copying the vertex array every frame). Those changes are currently only on the [develop branch](https://github.com/keenanwoodall/Deform/commit/3d3049d956ae968b1306a9c6e0e4cfe8bba54700) but will probably make their way into the next release. You can apply the changes to your installation of Deform manually or work off of the linked commit.

Here's the script:
```cs
using UnityEngine;
using Deform;

[ExecuteAlways]
public class AttachToTriangle : MonoBehaviour
{
	public struct Triangle
	{
		public Vector3 a, b, c;

		public void Multiply(Matrix4x4 m)
		{
			a = m.MultiplyPoint3x4(a);
			b = m.MultiplyPoint3x4(b);
			c = m.MultiplyPoint3x4(c);
		}

		public Vector3 GetPosition() => (a + b + c) / 3f;
		public Quaternion GetRotation() => Quaternion.LookRotation((c - b).normalized, (b - a).normalized);
	}

	public Deformable target;
	public int triangleIndex;
#if UNITY_EDITOR
	[SerializeField] private bool drawTriangle = true;
#endif
	private void Update()
	{
		if (target == null) 
			return;

		var data = target.GetDynamicManagedMeshData();
		if (data == null) 
		   return;

		triangleIndex = Mathf.Clamp(triangleIndex, 0, data.Triangles.Length / 3);

		var triangle = GetTriangle(data, triangleIndex);

		triangle.Multiply(target.transform.localToWorldMatrix);
#if UNITY_EDITOR
		if (drawTriangle)
			DrawTriangle(triangle);
#endif

		var newPosition = triangle.GetPosition();
		var newRotation = triangle.GetRotation();

		transform.SetPositionAndRotation(newPosition, newRotation);
	}

	public Triangle GetTriangle(ManagedMeshData data, int triangleIndex)
	{
		var vertexIndex = triangleIndex * 3;
		var triangles = data.Triangles;
		var vertices = data.Vertices;
		return new Triangle
		{
			a = vertices[triangles[vertexIndex + 0]],
			b = vertices[triangles[vertexIndex + 1]],
			c = vertices[triangles[vertexIndex + 2]]
		};
	}

	private void DrawTriangle(Triangle triangle)
	{
		Debug.DrawLine(triangle.a, triangle.b);
		Debug.DrawLine(triangle.b, triangle.c);
		Debug.DrawLine(triangle.c, triangle.a);
	}
}
```
![2019-10-26_12-45-59](https://user-images.githubusercontent.com/9631530/67623755-a2f8c400-f7ee-11e9-8cb3-389a38f52ae9.gif)

**Comment by nathanvogel** [comment]
Super cool! Thanks a lot, I really appreciate and I'll try it this week :)

**Comment by nathanvogel** [comment]
Hey! I'm working on another part of the project these days, but I tried your script and just wanted to give you some feedback: 
 - it works great 👍
 - I mostly use a setup like this: 
![image](https://user-images.githubusercontent.com/3106715/68128049-ecdc5b00-ff0e-11e9-8c0c-c25a43e8885b.png)
   - Original transform is just a 0,0,0 child transform.
   - Deformed triangle is a dummy triangle.
   - Where "Camera space" has a script that uses both the "Original transform" and the "Deformed transform" to compute a position (we need a different behavior outside a certain bounding box, and that behavior requires knowing both the original and the deformed position).
 - We're mostly using index 0, but even when using our (quite simple) terrain mesh, manually setting the index is easy.

Thanks again!

**Comment by keenanwoodall** [comment]
That's great to hear! 👍
