### ISSUE TITLE
Jitter on deformed mesh when rolling

### ISSUE THREAD

**Issue by michaelhighland** [keenanwoodall/Deform#35]
When using a deformer on a mesh that is rotating the deformed mesh jitters. I'm trying to apply a deformer to a rolling sphere and am seeing a lot of jittering at higher angular vels. Has anyone else seen this?

**Comment by keenanwoodall** [comment]
Can you send a recording or repro? Only reason I can think this would happen is from vertex positions have low precision from having very large values.

**Comment by lordubbe** [comment]
Hi! If I understand michael correctly I am having the same issue.
I have a GameObject with a deformer (SquashAndStretchDeformer) and a Deformable. The Mesh is a simple standard sphere primitive. When rotating the Transform in play mode the object "jitters", which is very jarring.
The same action works flawlessly outside of play mode.

Any help to reduce or eliminate this effect would be greatly appreciated!

GIF:
https://gyazo.com/87c597000fcd6bf63d9fa085c104a773

Components:
![image](https://user-images.githubusercontent.com/6771203/91633369-0db6f500-e9e8-11ea-9d21-951fd979dd59.png)

**Comment by keenanwoodall** [comment]
Ah I see now, thanks for the gif. 
This is due to how deformables update. Instead of starting the deformer calculations in Update and applying them in LateUpdate like you might expect, they get scheduled in Update and applied _on the next_ Update. This gives the worker threads an entire frame to work before the main thread has to wait on them to finish. This is great for performance, and works for most use-cases I've ran into, but introduces one frame of latency which is what's causing the jittering.

I'd like to integrate a better solution, but for now the easiest fix is to update the deformable yourself. Here's a script I wrote that you can add to the same game object as the deformable and it will update it immediately every frame.
```cs
using UnityEngine;
using Deform;

public class DeformableUpdater : MonoBehaviour
{
	public Deformable deformable;

	private void OnEnable ()
	{
		if (deformable == null && !TryGetComponent(out deformable))
			return;
		deformable.Manager = null;
		deformable.UpdateMode = UpdateMode.Custom;
	}
	private void OnDisable()
	{
		if (deformable == null)
			return;
		deformable.Complete();
	}
	private void Update ()
	{
		if (deformable == null)
			return;
		deformable.PreSchedule();
		deformable.Schedule ();
	}
	private void LateUpdate ()
	{
		if (deformable == null)
			return;
		deformable.Complete ();
		deformable.ApplyData ();
	}
}
```
![8sMHE53y2v](https://user-images.githubusercontent.com/9631530/91641409-c6316880-e9e9-11ea-920b-8b7bb7c31a16.gif)
Do note that updating it immediately will incur a performance penalty as the main thread will start waiting on the deformers jobs sooner; though it shouldn't make a big difference unless a lot of deformables update immediately 🙂

**Comment by lordubbe** [comment]
Thanks! It makes a lot of sense, and I suppose that the use case might be unique!
Thanks for the script as well, it works great with the standard Deformable: https://gyazo.com/c3cccf8c7c5586626983da9756b0d1ed
**However**, using the ElasticDeformable produces weird (but less jittery) results:  https://gyazo.com/1b8c5aa1d7627862255dbcd4f94a65bb

Additionally I'd like to point out to anyone else who might come across this thread in the future that a simple restart of unity solves the error spam after adding the component!

In case you would like to look into them I've provided the messages below:
`A Native Collection has not been disposed, resulting in a memory leak. Enable Full StackTraces to get more details.`
and
`InvalidOperationException: The previously scheduled job ElasticVertexUpdateJob writes to the NativeArray ElasticVertexUpdateJob.velocities. You are trying to schedule a new job ElasticVertexUpdateJob, which writes to the same NativeArray (via ElasticVertexUpdateJob.velocities). To guarantee safety, you must include ElasticVertexUpdateJob as a dependency of the newly scheduled job.
Unity.Jobs.LowLevel.Unsafe.JobsUtility.ScheduleParallelFor (Unity.Jobs.LowLevel.Unsafe.JobsUtility+JobScheduleParameters& parameters, System.Int32 arrayLength, System.Int32 innerloopBatchCount) (at <3dc54541a2574ac7826a004a212a4332>:0)
Unity.Jobs.IJobParallelForExtensions.Schedule[T] (T jobData, System.Int32 arrayLength, System.Int32 innerloopBatchCount, Unity.Jobs.JobHandle dependsOn) (at <3dc54541a2574ac7826a004a212a4332>:0)
Deform.ElasticDeformable.Schedule (Unity.Jobs.JobHandle dependency) (at Library/PackageCache/com.beans.deform@ecfca50f5f/Code/Runtime/Mesh/ElasticDeformable.cs:95)
DeformableUpdater.Update () (at Assets/DeformableUpdater.cs:31)
`

**Comment by lordubbe** [comment]
Just bumping - any chance there's a fix for the very weird behaviour with ElasticDeformable?

**Comment by keenanwoodall** [comment]
Thanks for the bump. I'm away a computer for the next week and a half, but I'll look into it again as soon as I can 👍

**Comment by lordubbe** [comment]
Awesome! Much appreciated - you rock!

**Comment by keenanwoodall** [comment]
Sorry for the delay, this was my first time moving and I vastly underestimated how much time it would take to get setup :P

---

I've tried to recreate your thin mesh setup with a Squash and Stretch deformer on a sphere. From what I could tell, the "weird behavior" you mention is lots of self intersection, but let me know if it's something else.
![TTyPQnzhhv](https://user-images.githubusercontent.com/9631530/96375452-ebab3a80-112d-11eb-9fac-62a2b919f8ff.gif)

I believe this is not technically a bug. It's just a limitation of the implementation. The elastic effect is applied to vertices individually. Each vertex is essentially attached to a target position via a spring. They are not affected by or attached to each other at all, so there's no "structural integrity" anywhere. Each vertice essentially operates in a vacuum and I think a thin rotating mesh is a tough scenario where the illusion of a coherent surface breaks.

I'm worried the behavior is just inherent to my simple "point on a spring" implementation. Without a more advanced simulation I can't think of a way to prevent the effect :( however if you have any thoughts or feel this is a misdiagnosis please let me know :)

**Comment by lordubbe** [comment]
I understand your diagnosis, however I'm not sure I agree! 
I guess it mostly comes down to expectations of behaviour... I am away from my computer at the time of writing, so forgive me if I recall incorrectly, but moving the parent transform does not produce the elastic effect. This gives the impression that the elasticity is relative to the transform that the deformer is on, or in other words, it's bound to **local** transformations rather than global.

So I guess what's "missing" is for rotations to also be relative to the local rotation (each vertex's relative position to the local origin), so that rotating a parent transform (thus not changing the local rotation) will not produce the elastic effect since each vertex remains at the same relative position, just like moving the parent transform doesn't produce the elastic effect as the vertices remain at the same relative position as well. 

Maybe my use case is unique, but I feel like what I describe is the intuitive behaviour, at least in the context of how things normally work in Unity hierarchies. If the current behaviour is desired in some situations, perhaps a toggle could be implemented? Think local space particles vs. world space particles.

I hope that makes sense!

Please do tell me if there's anything I can do to help or further explain! I'd also like to buy you a coffee for your efforts if you have such a thing set up!

Cheers!

**Comment by lordubbe** [comment]
Please disregard my previous reply.
Apologies for sending a reply before I got to test out and collect my thoughts. I ended up describing the problem. I will properly test and formulate a reply later! Sorry for the email spam (I will delete this reply as well)
