### ISSUE TITLE
Is managed data still needed?

### ISSUE THREAD

**Issue by HitCache** [keenanwoodall/Deform#40]
@keenanwoodall Since latest versions of Unity support Mesh.SetVertices, Mesh.SetNormals, etc with native arrays I was wondering if we still need to do this step?

**From MeshData.cs:**
```
// Copy the native data into the managed data for efficient transfer into the actual mesh.
DataUtils.CopyNativeDataToManagedData(dynamicManaged, DynamicNative, dataFlags);
```

I have tried bypassing it and doing this instead and it works fine, I think it might be more efficient since we can skip the managed overhead entirely?
```
if ((dataFlags & DataFlags.Vertices) != 0)
				DynamicMesh.SetVertices(DynamicNative.VertexBuffer);
			if ((dataFlags & DataFlags.Normals) != 0)
				DynamicMesh.SetNormals(DynamicNative.NormalBuffer);
			if ((dataFlags & DataFlags.Tangents) != 0)
				DynamicMesh.SetTangents(DynamicNative.TangentBuffer);
			if ((dataFlags & DataFlags.UVs) != 0)
				DynamicMesh.SetUVs(0,DynamicNative.UVBuffer);
			if ((dataFlags & DataFlags.Colors) != 0)
				DynamicMesh.SetColors(DynamicNative.ColorBuffer);
...etc...
```

If not then there is separate optimization I'd like to propose/implement that will be faster than MemCpy (see bottom of this page if curious: https://jacksondunstan.com/articles/4713 where `CopyFromFast` and `CopyToFast` is discussed)

Just want to get some thoughts on this in case I'm missing something, otherwise I'm thinking about stripping out the managed data stuff and submitting a pull request!

**Comment by keenanwoodall** [comment]
Preprocessor stuff has been added so it uses managed data before 2019.3
I made a test fbx with submeshes to see how it breaks and realized it wasn't going to break because no deformer (that I've made) marks the triangles as changed in the data flags so it never gets copied.

I removed the data flags check so it always copies the triangles and the result was the first material being applied to the entire mesh since it was treated as one submesh. Was that how it broke for you, or did it do something else? Did you have a custom deformer that was modifying the triangles? I'm curious what caused the break.

I tried changing the code that sets the indices to this
```cs
if ((dataFlags & DataFlags.Triangles) != 0)
{
	for (int i = 0; i < to.subMeshCount; i++)
	{
		var submesh = to.GetSubMesh(i);
		to.SetIndices
		(
			indices: 		from.IndexBuffer,
			indicesStart: 		submesh.indexStart, 
			indicesLength:		submesh.indexCount, 
			topology: 		submesh.topology, 
			submesh: 		i, 
			calculateBounds: 	false, 
			baseVertex: 		submesh.baseVertex
		);
	}
}
```
it's on develop and it seems to work as well 👍

**Comment by HitCache** [comment]
No custom deformers involved.

Materials were fine just all submeshes were straight up missing, except for the very first 0 index submesh.

Thanks, I will get to testing this very soon! If it breaks again I will try get you a repro case or something.
