### ISSUE TITLE
Apply Deformable to all MeshFilter Childs

### ISSUE THREAD

**Issue by usernameHed** [keenanwoodall/Deform#57]
Hello, I would like to know if it's currently possible. I have a prefab with +10 mesh inside.
I saw that if I create for each child's gameObjects an Deformable Components, it obviously work if I setup for each of them the same deformer.

But I wonder if we could have an option in the Deformable to say "Apply to childs" or something. I wonder if the way I do is the good way.

Also: when I'm adding a Deformer from the Creator Window, selected on a gameObject, I would like it to add itself to EVERY deformable childs.

**Comment by keenanwoodall** [comment]
Currently, the easiest way to automatically make all children deformable is via the `Tools/Deform/Actions/Make All Children Deformable` menu item. This will find all children with a `MeshFilter` or `SkinnedMeshRenderer` and add a Deformable component to them. It also selects all of the valid child game objects so that you can more easily add a Group or Auto Group deformer.

![5BlAnDJOpc](https://user-images.githubusercontent.com/9631530/134268159-e2f80a6e-543a-4339-b604-ea13e43376da.gif)
