### ISSUE TITLE
Update the MeshCollider

### ISSUE THREAD

**Issue by IwakuraRein** [keenanwoodall/Deform#79]
Hi. I noticed that `Deformable.RecalculateMeshCollider()` simply replaced the `MeshCollider.sharedMesh` and let Unity rebuild the collider.

I am curious if Unity can expose mesh collider's vertices so we can explicitly edit them with job system, simlarly as how we edit the mesh?

**Comment by keenanwoodall** [comment]
To my knowledge, the only way to update a mesh collider's mesh is to set the `sharedMesh` property. I would be interested in a way to manually update the internal mesh collider data since reassigning the mesh is expensive, but it [does not appear to be possible at this time](https://docs.unity3d.com/Manual/class-MeshCollider.html#:~:text=You%20should%20not,spheres%20and%20boxes.) :(

> You should not modify mesh geometry that is used for colliders because the physics engine has to rebuild an internal mesh collision acceleration structure every time you change the mesh. This causes a substantial performance overhead. For meshes that need to collide and change at runtime, it is often better to approximate the mesh shape with primitive colliders like capsules, spheres and boxes.
